# Generated by Django 4.2.4 on 2023-12-30 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0001_initial'),
    ]

    operations = [
    ]
